import Head from 'next/head';
import Alert from '../components/Alert';
import EndBenner from '../components/EndBenner';
import Explore from '../components/Explore';
import Fotter from '../components/Fotter';
import HeroSection from '../components/HeroSection';
import LiveAnywhere from '../components/LiveAnywhere';
import SigninModel from '../components/SinginModel';
export default function Home({ fatchingData, fatchingCartData }) {
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HeroSection />

        <SigninModel />
        <Alert />
        <div className="max-w-screen-2xl mx-auto px-10">
          <Explore fatchExploreData={fatchingData} />
          <LiveAnywhere fatchingCartData={fatchingCartData} />
          <EndBenner />
        </div>
        <Fotter />
      </div>
    </div>
  );
}
export const getStaticProps = async () => {
  const fatchingData = await fetch('https://links.papareact.com/pyp').then(
    (res) => res.json()
  );
  const fatchingCartData = await fetch('https://links.papareact.com/zp1').then(
    (res) => res.json()
  );

  return {
    props: {
      fatchingData,
      fatchingCartData,
    },
  };
};
